# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "main"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
    groups:
      update-react-native:
        patterns:
          - "react-native"
          - "@react-native/*"
          - "@types/react"
          - "react"
      update-jest:
        patterns:
          - "jest"
          - "@types/jest"
      update-textlint:
        patterns:
          - "textlint"
          - "textlint-*"
          - "@textlint-ja/*"
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 10
    schedule: 
      interval: "monthly"